export const ADD_EVENT_REQUEST = 'GET_ALL_EVENT_REQUEST';
export const ADD_EVENT_SUCCESS = 'GET_ALL_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE = 'GET_ALL_EVENT_FAILURE';
  
// export const ADD_EVENT_REQUEST = 'GET_ALL_EVENT_REQUEST';
// export const ADD_EVENT_SUCCESS = 'GET_ALL_EVENT_SUCCESS';
// export const ADD_EVENT_FAILURE = 'GET_ALL_EVENT_FAILURE';
  